### ISSUE TITLE
about dub.json how to write

### ISSUE THREAD

**Issue by heketang** [msoucy/dproto#111]
hi;
when i  test   " mixin ProtocolBuffer!"person.proto" ",it occurred a error. 

error"need -Jpath switch to import text file person.proto
source/app.d(4,1): Error: mixin app.ProtocolBuffer!"person.proto" error instantiating"

the person.proto , i put  it and app.d at same level .
thanks;

**Comment by msoucy** [comment]
The current directory will need to be listed in a `stringImportPaths` field. See http://code.dlang.org/package-format?lang=json for more information
