### ISSUE TITLE
Can you expand to automatically read fields

### ISSUE THREAD

**Issue by heketang** [msoucy/dproto#112]
example：
message ms;
auto names = ms.arr_names;
foreach(name;names)
{
       auto value =ms.name;        
}

**Comment by heketang** [comment]
thinks ,i have do the work.

**Comment by timotheecour** [comment]
standard protobufs have a reflection API (https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.message) but thanks to dproto using compile time generation and CTFE, can't we use D's builtin functionality for this?

eg:
`foreach(memberName; __traits(allMembers, YourClass)) {...}`

would that work?

**Comment by msoucy** [comment]
Indeed, using D's builtin compile time reflection is the preferable way to do this, in order to stay as idiomatic to D as possible.

**Comment by heketang** [comment]
@msoucy  @timotheecour , Thanks, the reflection of dlang is so strong.
