### ISSUE TITLE
Create 1.x.x / 1.3.x branch 

### ISSUE THREAD

**Issue by Marenz** [msoucy/dproto#120]
Given that v2 [removed some functionality](https://github.com/msoucy/dproto/issues/80) crucial to maybe some users and dmd keeps updating and introducing deprecations to old code, would you be willing to create branches for the v1 based versions and accept pull requests to it, including creation of new tags for deployment on the dub registry?

**Comment by msoucy** [comment]
I've pushed a `dev-1.x` branch - I don't plan on actively developing it, but I'll certainly take a look at any pull requests that are made for it.

**Comment by Marenz** [comment]
thank you!
