### ISSUE TITLE
Range support

### ISSUE THREAD

**Issue by msoucy** [msoucy/dproto#13]
Deserializers should handle any arbitrary input range of ubyte, not just ubyte[].

By the same reasoning, serializers should handle output ranges.

**Comment by MartinNowak** [comment]
Can this be closed now?
Should also release a new version 1.1.2.

**Comment by msoucy** [comment]
I believe it can. Did your testing find anything else that needs to be taken care of with range support?

**Comment by MartinNowak** [comment]
I think I found a bug when decoding nested messages, but that needs a little more investigation.

**Comment by msoucy** [comment]
SYN - status?

**Comment by MartinNowak** [comment]
> SYN - status?

Sorry, no time right now, busy with release building.

**Comment by msoucy** [comment]
No worries, take your time

**Comment by MartinNowak** [comment]
I can no longer reproduce the bug, maybe my D test server and the python client were out of sync.

**Comment by msoucy** [comment]
Alright, in that case I'll close this and push the next release!

**Comment by MartinNowak** [comment]
Thanks, I haven't yet benchmarked/profiled receiving, but work on that shouldn't affect the API.
