### ISSUE TITLE
git log shows nonlinear history; please use rebase instead of pull 

### ISSUE THREAD

**Issue by timotheecour** [msoucy/dproto#132]
FYI @msoucy thanks :)

**Comment by msoucy** [comment]
When most pull requests were merged, it was done via the github webpage, which (at the time) didn't provide a way to merge via fast-forward. It's something I'll keep in mind in the future.

**Comment by timotheecour** [comment]
ok; btw, if you don't mind, could you update dub proto package to point to latest?
thanks!
