### ISSUE TITLE
dmd buildkite picking v2.1.4 tag

### ISSUE THREAD

**Issue by RazvanN7** [msoucy/dproto#136]
Hi! Currently the dmd buildkite agent is picking tag v2.1.4 to test new PRs. This is currently blocking this PR: [1] . The error is : [2] . I thought I would fix the error, but I see that your master branch has already took care of that (the identity template is declared and wrongfully imported via traits - I say wrongfully because Identity is actually declared in std.conv). Could you please push a new tag with your master so that we can keep going with [1] ? Thanks!

[1] https://github.com/dlang/dmd/pull/9393
[2] https://buildkite.com/dlang/dmd/builds/4891#05584530-2de2-4c7e-821e-a00fc5e0fa70

**Comment by msoucy** [comment]
Tagged 2.1.5, sorry about that.

**Comment by RazvanN7** [comment]
Thanks! I can confirm that the project is no longer failing in buildkite.

**Comment by msoucy** [comment]
Sounds good, thank you for the notification!
