### ISSUE TITLE
Possibility of Boost license

### ISSUE THREAD

**Issue by Downchuck** [msoucy/dproto#38]
In keeping with the standards among D libraries, could this project be dual licensed with a Boost license?

**Comment by msoucy** [comment]
Relicensing would require contacting the other contributors - I'm taking a look at licenses and the logistics of dual-licensing.

**Comment by msoucy** [comment]
@Kelet @MartinNowak @cporter

While I'm looking at licensing and the licenses involved, how do you all feel about either dual-licensing or changing the license to the [Boost Software License](http://www.boost.org/users/license.html)?

**Comment by MartinNowak** [comment]
MIT, Boost and BSD-3 are all copyfree http://copyfree.org/standard/licenses, so I don't see a point in changing this. I don't care though, so do what you think makes sense.

**Comment by Kelet** [comment]
I have the same thoughts as @MartinNowak

**Comment by msoucy** [comment]
The main difference between BSD-3 and Boost (that I can see) is that Boost doesn't require binary distributions that use the code (ex: executables that contain dproto-generated code) to have the license attached. This would reduce attribution in commercial software, but make it easier for users to remain compliant with the license.

**Comment by msoucy** [comment]
Sorry @Downchuck, but I don't see enough of a reason to dual license...

**Comment by Downchuck** [comment]
I disagree: D standard libraries are Boost licensed.

An application written in standard D, using dproto, would now have license requirements in release documents -- it otherwise would not. dproto is like the D standard libraries (phobos), a utility library with a specific function (serialization).

The issue I have with the license is about the target audience: vibe.d is a great example of maintaining an attribution license, as it is run on the server side. pegged is a great example of using boost "Pegged is released with the Boost license (like most D projects)" as it is a library intended to be used to generate client-side code.

There is very little value in requiring that developers maintain a license list for end-users who have no programming knowledge (or any idea what the language "D" is).

Meanwhile, there is a cost in requiring developers to clear a new license and to ensure that the license is properly packaged so that end users can access that license in a README document or other help format form.

-Charles

**Comment by msoucy** [comment]
That is actually fairly convincing... Reopening so I can do it when I'm not on my phone
