### ISSUE TITLE
Release 1.2.5

### ISSUE THREAD

**Issue by Downchuck** [msoucy/dproto#53]
There are a good amount of updates in the current master, let's figure out how to get it ready for a 1.2.5 release.

**Comment by msoucy** [comment]
Yikes, I didn't realize it had been so long. I'll do that when I get home. I was hoping to get #52 done before the next release, but the uda branch will probably (hopefully) make it irrelevant.

**Comment by Downchuck** [comment]
Do you need some kind of assist/review on that UDA branch?

**Comment by msoucy** [comment]
What I need is a chance to actually sit down and really work on it...didn't realize my job would leave me so drained this summer. Making a bit of progress though.

**Comment by msoucy** [comment]
v1.3.0 has been created - significant improvements seemed to warrant more than just a patch number bump.
