### ISSUE TITLE
is there some doc on what's currrently supported from proto api?

### ISSUE THREAD

**Issue by timotheecour** [msoucy/dproto#70]
is the binary serialization compatible with standard ?
what about proto extensions?
can parse proto files that contain proto imports?

**Comment by msoucy** [comment]
Binary compatible for everything that's implemented (so missing the extension ability, support for proto3 types like Any, the datetime types, the map types)

I'll write a more proper document within the next few days.

**Comment by msoucy** [comment]
Fixed via 758db614e1e06383d0754c102f34c1b3e5cfd1a8
