### ISSUE TITLE
please add in https://github.com/google/protobuf/wiki/Third-Party-Add-ons

### ISSUE THREAD

**Issue by timotheecour** [msoucy/dproto#72]
it lists:
D: http://256.makerslocal.org/wiki/index.php/ProtocolBuffer
D: https://github.com/opticron/ProtocolBuffer

but these projects seem older and not maintained (=>2013)

would be nice to have this listed there to increase visibility

maybe also add a note for how it compares to those 2 (defunct?) projects

**Comment by msoucy** [comment]
I've sent a message to the protobuf mailing list, though it appears to have vanished into the bit bucket. I'll give it a bit of time in case it got caught in a filter.

**Comment by msoucy** [comment]
It has been added to the list!
